kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - cp -rf /root/cloned_repo/discution-app-back/.env .
      - docker build -t discutoi:back .

  - name: stop-previous-version
    commands:
      - docker rm -f discutoi-back || true

  - name: deploy
    commands:
      - docker run -d -p 8051:3000 --name discutoi-back discutoi:back
